// action types
export const LOAD_REFERENCE_FAILURE = 'LOAD_REFERENCE_FAILURE'
export const LOAD_REFERENCE_REQUEST = 'LOAD_REFERENCE_REQUEST'
export const LOAD_REFERENCE_SUCCESS = 'LOAD_REFERENCE_SUCCESS'

export const HYDRATE_CHAPTERS = 'HYDRATE_CHAPTERS'

export const LOAD_LANGUAGE = 'LOAD_LANGUAGE'
export const LOAD_VERSION = 'LOAD_VERSION'
export const LOAD_CHAPTER = 'LOAD_CHAPTER'
export const LOAD_BOOK = 'LOAD_BOOK'

export const SET_SITE_PATH = 'SET_SITE_PATH'
export const SET_SITE_BRAND_PATH = 'SET_SITE_BRAND_PATH'
export const SET_SITE_TITLE = 'SET_SITE_TITLE'

export const SET_READER_FONT_STYLE = 'SET_READER_FONT_STYLE'
export const SET_READER_LINE_BREAK = 'SET_READER_LINE_BREAK'
export const SET_READER_TEXT_ALIGN = 'SET_READER_TEXT_ALIGN'
export const SET_READER_TEXT_DIRECTION = 'SET_READER_TEXT_DIRECTION'
export const SET_READER_VERSE_DISPLAY = 'SET_READER_VERSE_DISPLAY'
